---
# control
control:
  num_supervised: '4000'
  loss_mode: 'fix-mix'
  num_clients: '100'
  active_rate: '0.1'
  data_split_mode: 'iid'
  local_epoch: '5'
  gm: '0.5'
  sbn: '1'
  ft: '1'
# data
data_name: CIFAR10
model_name: wresnet28x2
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
